// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4B_QetQFEWL7GEpKRr2ybNCRBQKHFKQ',
    appId: '1:741098087182:web:b829a40e6e28b3abc4ed5f',
    messagingSenderId: '741098087182',
    projectId: 'sevapani-e660c',
    authDomain: 'sevapani-e660c.firebaseapp.com',
    storageBucket: 'sevapani-e660c.firebasestorage.app',
    measurementId: 'G-QG86W422RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKntgEI2lvsrM1VYhCDps0qrf7DS_5D8I',
    appId: '1:741098087182:android:18cf45d4931ab343c4ed5f',
    messagingSenderId: '741098087182',
    projectId: 'sevapani-e660c',
    storageBucket: 'sevapani-e660c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQh39iLFxNiN3l0olhdMQvZp0aMOiRJHo',
    appId: '1:741098087182:ios:3631876aaa69e87fc4ed5f',
    messagingSenderId: '741098087182',
    projectId: 'sevapani-e660c',
    storageBucket: 'sevapani-e660c.firebasestorage.app',
    iosBundleId: 'com.example.nriTrial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQh39iLFxNiN3l0olhdMQvZp0aMOiRJHo',
    appId: '1:741098087182:ios:3631876aaa69e87fc4ed5f',
    messagingSenderId: '741098087182',
    projectId: 'sevapani-e660c',
    storageBucket: 'sevapani-e660c.firebasestorage.app',
    iosBundleId: 'com.example.nriTrial1',
  );

}